name: Selenium Tests with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: ''

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Build with Gradle and Run Tests
        run: ./gradlew clean test

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: build/allure-results/

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/reports/allure-report/
