name: Selenium Tests with Allure Reporting on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 21 with Temurin distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Set up Chrome browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      # Set up ChromeDriver for Selenium tests
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # Build the project and run the tests using Gradle
      - name: Build with Gradle and Run Tests
        run: |
          # Set display for running in headless mode
          export DISPLAY=:99
          
          # Start ChromeDriver in the background
          chromedriver --url-base=/wd/hub &
          
          # Start a virtual display to support graphical rendering (headless mode)
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          
          # Run Gradle tests and generate Allure report
          ./gradlew clean test allureReport

      # Fetch previous Allure history from gh-pages branch
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history

      # Generate the Allure report
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20

      # Deploy the generated Allure report to GitHub Pages (gh-pages branch)
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
